spring:
  application:
    name: '02_kafka_demo'

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: my-group
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer